import { Flex } from "@chakra-ui/react";
import { motion } from "framer-motion";
import Head from "next/head";
import React, { useState } from "react";

import ConversationsWrapper from "../components/Conversations/ConversationsWrapper";
import FeedWrapper from "../components/Feed/FeedWrapper";
import { MessageBody } from "../components/Feed/Messages";

type Props = {};

function ChatRoom({}: Props) {
  const [lastSeenMessage, setLastSeenMessage] = useState<MessageBody[]>([]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>

      <Flex height="100vh" overflow="hidden">
        <ConversationsWrapper lastSeenMessage={lastSeenMessage} />
        <FeedWrapper setLastSeenMessage={setLastSeenMessage} />
      </Flex>
    </motion.div>
  );
}

export default ChatRoom;
