import { Flex } from "@chakra-ui/react";
import { motion } from "framer-motion";
import Head from "next/head";

import ConversationsWrapper from "../components/Conversations/ConversationsWrapper";
import FeedWrapper from "../components/Feed/FeedWrapper";

type Props = {};

function ChatRoom({}: Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <Flex height="100vh" overflow="hidden">
        <ConversationsWrapper />
        <FeedWrapper />
      </Flex>
    </motion.div>
  );
}

export default ChatRoom;
